Feature/84572 Make checklistpage look like the checklistpage in mc
equinor/procosys-commissioning-webapp pull request #155
Opened 2022-03-17 17:44 UTC by Prestholm

AB#84572

2022-03-23 10:05 UTC, VRiveland requested changes

2022-03-23 10:05 UTC, VRiveland commented on src/pages/Checklist/ChecklistPage.tsx
> +                                history.push(
This doesn't work. According to the general router component this url needs either verify or clear at the end

2022-03-24 10:52 UTC, Prestholm commented on src/pages/Checklist/ChecklistPage.tsx
> +                        <TagInfoWrapper tagId={details?.checkList.tagId} />
Har etterspurt endring i Main API-et fra Elisabeth

2022-03-29 10:14 UTC, VRiveland commented on src/pages/Punch/NewPunch/NewPunchSuccessPage.tsx
> +                            `/${params.plant}/${params.project}/${params.searchType}/${params.entityId}/checklist/${params.checklistId}`
Could you not just remove 2 subdirectories here? Instead of re-writing the whole URL

2022-03-29 10:14 UTC, VRiveland commented on src/services/procosysApi.ts
> +    const getTag = async (
Already a function for this. The getEntityDetails function returns a tag if you pass in SearchType.Tag as searchtype

2022-03-29 10:14 UTC, VRiveland commented on src/services/procosysApi.ts
> +    const getTag = async (
Also, no functions in this file is to be placed above the getVersion function.

2022-04-01 07:12 UTC, VRiveland approved these changes

2022-04-01 07:12 UTC, VRiveland commented on src/pages/Checklist/ChecklistPage.tsx
> +    const [refreshChecklistStatus, setRefreshChecklistStatus] = useState(false);
This state variable is never updated, as the setter is unused. The getter is only used in the useEffect to run the useEffect when the setter is used. As the setter is never used, neither is the getter. Any state variable where only one of the getter or setter is used is useless and should be removed. Please do so.

2022-04-01 07:41 UTC, merged